### PR TITLE
rebase works against app/run images with tags that aren't latest

### LINKED ISSUE #166: rebase fails if the image being rebased has no latest tag

### PR DESCRIPTION
**Pull request by ashwin-venkatesh**
closes #166

### CODE REVIEW

File: pkg/cnb/image_rebaser_test.go [hunk 1]
```diff
@@ -47,60 +39,36 @@ func testImageRebaser(t *testing.T, when spec.G, it spec.S) {
...
+			newRunImage := fakes.NewImage("foo.io/run:basecnb", "0fd6395e4fe38a0c089665cbe10f52fb26fc64b4b15e672ada412bd7ab5499a0", &fakeImageIdentifier{identifier: "foo.io/run@sha256:0fd6395e4fe38a0c089665cbe10f52fb26fc64b4b15e672ada412bd7ab5499a0"})
+			require.NoError(t, newRunImage.SetLabel("io.buildpacks.stack.id", "io.buildpacks.stacks.bionic"))
 
-			rebasedAppImage := fakes.NewImage("testimage/app", "980723452toplayer", &fakeImageIdentifier{identifier: "rebasedappimage"})
-			err = rebasedAppImage.SetLabel("io.buildpacks.build.metadata", `{"buildpacks": [{"id": "test.id", "version": "1.2.3"}]}`)
-			require.NoError(t, err)
-			err = rebasedAppImage.SetLabel("io.buildpacks.lifecycle.metadata", `{"runImage":{"topLayer":"sha256:719f3f610dade1fdf5b4b2473aea0c6b1317497cf20691ab6d184a9b2fa5c409","reference":"localhost:5000/node@sha256:0fd6395e4fe38a0c089665cbe10f52fb26fc64b4b15e672ada412bd7ab5499a0"},"stack":{"runImage":{"image":"testbuilder/run:full-cnb"}}}`)
-			require.NoError(t, err)
-			fakeRemoteImageFactory.NewRemoteReturnsOnCall(3, rebasedAppImage, nil)
+			fakeRemoteImageFactory.NewRemoteReturnsForImageName("testbuilder/builder", builderImage)
```
Comment (matthewmcnew) [inline pkg/cnb/image_rebaser_test.go]: Just because this is the major point of confusion, can we make this include all the arguments to NewRemote?

File: pkg/cnb/image_util_factory.go [hunk 2]
```diff
@@ -12,19 +11,14 @@ type ImageFactory struct {
...
 	keychain, err := f.KeychainFactory.KeychainForSecretRef(secretRef)
 	if err != nil {
 		return nil, err
 	}
-	imageRef, err := name.ParseReference(image)
-	if err != nil {
-		return nil, err
-	}
-	return remote.NewImage(imageRef.Context().Name(), keychain, remote.FromBaseImage(image))
+	return remote.NewImage(imageName, keychain, remote.FromBaseImage(baseImage))
```
Comment (matthewmcnew) [inline pkg/cnb/image_util_factory.go]: I'm inclined to wrap this error in pkg/errors?

File: pkg/cnb/image_rebaser.go [hunk 3]
```diff
@@ -49,32 +48,23 @@ func (f *ImageRebaser) Rebase(build *v1alpha1.Build, ctx context.Context) (Built
...
 
-	newBaseImage, err := f.RemoteImageFactory.NewRemote(metadata.Stack.RunImage.Image, registry.SecretRef{
+	newBaseImage, err := f.RemoteImageFactory.newRemote(metadata.Stack.RunImage.Image, metadata.Stack.RunImage.Image, registry.SecretRef{
 		Namespace:        build.Namespace,
 		ImagePullSecrets: build.Spec.Builder.ImagePullSecrets,
-		ServiceAccount:   build.Spec.ServiceAccount,
 	})
 	if err != nil {
-		return BuiltImage{}, errors.Wrap(err, "unable to fetch remote run image")
+		return BuiltImage{}, err
```
Comment (joaopapereira) [inline pkg/cnb/image_rebaser.go]: Why did we stop wrapping this error?

File: pkg/cnb/image_rebaser_test.go [hunk 4]
```diff
@@ -112,3 +80,23 @@ type fakeImageIdentifier struct {
...
+func (f *FakeRemoteImageUtilFactory) newRemote(imageName string, baseImage string, secretRef registry.SecretRef) (imgutil.Image, error) {
+	for imgName, fakeImage := range f.fakeImages {
+		if strings.Contains(baseImage, imgName) {
+			return fakeImage, nil
+		}
+	}
+	return nil, errors.New("not found")
+}
+
+func (f *FakeRemoteImageUtilFactory) NewRemoteReturnsForImageName(imageName string, image *fakes.Image) {
```
Comment (joaopapereira) [inline pkg/cnb/image_rebaser_test.go]: Does this need to be public?

File: pkg/cnb/image_rebaser_test.go [hunk 5]
```diff
@@ -1,19 +1,19 @@
-package cnb_test
+package cnb
```
Comment (joaopapereira) [inline pkg/cnb/image_rebaser_test.go]: Did we move this to `cnb` to make `newRemote` private?

File: pkg/cnb/image_rebaser.go [hunk 6]
```diff
@@ -21,16 +21,15 @@ type ImageRebaser struct {
 }
 
 func (f *ImageRebaser) Rebase(build *v1alpha1.Build, ctx context.Context) (BuiltImage, error) {
-	builderImage, err := f.RemoteImageFactory.NewRemote(build.Spec.Builder.Image, registry.SecretRef{
+	builderImage, err := f.RemoteImageFactory.newRemote(build.Spec.Builder.Image, build.Spec.Builder.Image, registry.SecretRef{
 		Namespace:        build.Namespace,
 		ImagePullSecrets: build.Spec.Builder.ImagePullSecrets,
-		ServiceAccount:   build.Spec.ServiceAccount,
```
Comment (joaopapereira) [inline pkg/cnb/image_rebaser.go]: Will there be any case where ImagePullSecrets are empty and kpack as to rely on the service account to get credentials for a private builder?

File: pkg/cnb/image_rebaser_test.go (hunk 5 above)
Comment (ashwin-venkatesh) [reply pkg/cnb/image_rebaser_test.go]: yes

File: pkg/cnb/image_rebaser.go (hunk 3 above)
Comment (matthewmcnew) [reply pkg/cnb/image_rebaser.go]: `newRemote` wraps the error. No need to wrap it again.

File: pkg/cnb/image_rebaser_test.go (hunk 4 above)
Comment (matthewmcnew) [reply pkg/cnb/image_rebaser_test.go]: It doesn't need to be exported but, is only accessible inside of the cnb_test package. So, it is not really accessible.

File: pkg/cnb/image_rebaser.go (hunk 6 above)
Comment (matthewmcnew) [reply pkg/cnb/image_rebaser.go]: No. kpack should not use the build's service account to fetch the builder.
