### PR TITLE
Error when blob url cannot be fetched

### LINKED ISSUE #426: Prepare step should error when a source blob is inaccessible or invalid
## What Happens
Currently, when an inaccessible or invalid blob url is provided to the prepare step the prepare step will complete without error and the build will fail when detect runs against an empty workspace. 

This is because when the prepare step fetches a provided source blob url it will attempt to unpack the blob even if a non 200 status code is returned. This is additionally problematic because the fetch will [ignore unexpected file types](https://github.com/pivotal/kpack/blob/e075180cb39b2898928973d0469fba9fc2172c4e/pkg/blob/fetch.go#L48) and exit with a success. 

## Reproduce
* Create an image with a `spec.source.blob.url` of something that does not exist like: `https://storage.googleapis.com/INVALID.jar`
* See this errored build: 

```
===> PREPARE
Loading secret for "****" from secret "***" at location "/var/build-secrets/***"
Successfully downloaded storage.googleapis.com/INVALID.jar in path "/workspace"
===> DETECT
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
```

### PR DESCRIPTION
**Pull request by tylerphelan**
Resolves #426

### CODE REVIEW

**Comment by matthewmcnew** [comment]
Part of what made this bug so mysterious is that we silently exit if an unexpected fileType appears. Could we update this PR to also exit when an unexpected fileType is provided even if it returns a 200 status code?

File: pkg/blob/fetch.go [hunk 1]
```diff
@@ -65,7 +73,18 @@ func (f *Fetcher) Fetch(dir string, blobURL string) error {
 		if err != nil {
 			return err
 		}
+
+		if !isTar(r){
```
Comment (tylerphelan) [inline pkg/blob/fetch.go:77]: i like keeping `isTar` outside of `extractTar` because
- `isTar` requires a `Seek(0,0)` to reset the reader but if we use a `ReadSeeker` as the arg to `extractTar` we lose the ability to use `gzip.NewReader(r)` as the reader which is nice to have.
- I think `isTar` is meant as a last check validation that the file is the type we expect, which I think is a different responsibility than validating that the input to `extractTar` is a tar file. we're able to cleanly handle the `unexpectedBlobTypeError` in this way.

Comment (tylerphelan) [reply pkg/blob/fetch.go:77]: @matthewmcnew

Comment (matthewmcnew) [reply pkg/blob/fetch.go:77]: That makes sense.
