### PR TITLE
Remove dependency on buildpack/imgutil

### LINKED ISSUE #128: Builder.Spec.Image does not support images with digest
Currently, kpack cannot process builders with an image that includes a digest. 

```yaml
apiVersion: build.pivotal.io/v1alpha1
kind: Builder
metadata:
  name: sample-builder
spec:
  image: cloudfoundry/cnb:bionic@sha256:b100bb7ba4d9109146965dbba0c91784bef2789b4fca759f4e734d55ea89a6af
```
Will fail to successfully reconcile the builder. 

kpack controller logs:
```
a digest must contain exactly one '@' separator (e.g. registry/repository@digest) saw: cloudfoundry/cnb:bionic@sha256:b100bb7ba4d9109146965dbba0c91784bef2789b4fca759f4e734d55ea89a6af@sha256:b100bb7ba4d9109146965dbba0c91784bef2789b4fca759f4e734d55ea89a6af
creating digest reference
```

### PR DESCRIPTION
**Pull request by matthewmcnew**
- Create GGCRImage that implements RemoteImage interface
- Fixes #128
- Upgrades lifecycle to 0.0.4

### CODE REVIEW

File: pkg/registry/ggcr_image.go [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+	"time"
+
+	"github.com/google/go-containerregistry/pkg/authn"
+	"github.com/google/go-containerregistry/pkg/name"
+	v1 "github.com/google/go-containerregistry/pkg/v1"
+	"github.com/google/go-containerregistry/pkg/v1/remote"
+	"github.com/pkg/errors"
+)
+
+type GGCRImage struct {
```
Comment (ashwin-venkatesh) [inline pkg/registry/ggcr_image.go]: Not sure if `GGCR` is how the community refers to the library. We could call it `RegistryImage` possibly? That or even `RemoteImage` 🤷‍♂

File: pkg/registry/ggcr_image.go [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+	image    v1.Image
+	repoName string
+}
+
+func NewGGCRImage(repoName string, keychain authn.Keychain) (*GGCRImage, error) {
```
Comment (ashwin-venkatesh) [inline pkg/registry/ggcr_image.go]: Do we want to call it `GetRemoteImage` or something similar, because we do not want to create an image in case one doesn't exist right? We only want to fetch an already existing one.

File: pkg/registry/image_factory.go [hunk 3]
```diff
@@ -3,19 +3,16 @@ package registry
...
-	"github.com/buildpack/imgutil/remote"
 	"github.com/google/go-containerregistry/pkg/authn"
-	"github.com/pkg/errors"
 )
 
 type ImageFactory struct {
 	KeychainFactory KeychainFactory
 }
 
 func (f *ImageFactory) NewRemote(imageRef ImageRef) (RemoteImage, error) {
```
Comment (ashwin-venkatesh) [inline pkg/registry/image_factory.go]: As an extension of our previous comment, can we update this as well to say `Get/FetchRemote` because it will never be our intent on actually creating a new remote image

File: pkg/cnb/cnb_metadata.go [hunk 4]
```diff
@@ -57,23 +57,23 @@ func (r *RemoteMetadataRetriever) GetBuilderImage(repo registry.ImageRef) (Build
 
 	return BuilderImage{
 		BuilderBuildpackMetadata: metadata.Buildpacks,
-		Identifier:               identifier.String(),
+		Identifier:               identifier,
```
Comment (ashwin-venkatesh) [inline pkg/cnb/cnb_metadata.go]: should this be Image too?

File: pkg/dockercreds/access_checker.go [hunk 5]
```diff
@@ -2,27 +2,31 @@ package dockercreds
 
 import (
 	"fmt"
+	"github.com/google/go-containerregistry/pkg/name"
```
Comment (ashwin-venkatesh) [inline pkg/dockercreds/access_checker.go]: import order nit

File: pkg/cnb/cnb_metadata.go (hunk 4 above)
Comment (matthewmcnew) [reply pkg/cnb/cnb_metadata.go]: That is an actual built image identifier. Not the same thing as an image because it always includes the digest

File: out.yaml [hunk 6]
```diff
@@ -0,0 +1,217 @@
+apiVersion: v1
```
Comment (ashwin-venkatesh) [inline out.yaml]: Checked in by mistake?

File: pkg/dockercreds/access_checker.go [hunk 7]
```diff
@@ -60,21 +64,3 @@ func HasWriteAccess(tagName string) (bool, error) {
 
 	return true, nil
 }
-
-type unAuthorizedWithoutErrorCodeTransportChecker struct {
```
Comment (c-abramson) [inline pkg/dockercreds/access_checker.go]: does the new version of ggcr make this obsolete?

File: pkg/registry/ggcr_image.go [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+	"time"
+
+	"github.com/google/go-containerregistry/pkg/authn"
+	"github.com/google/go-containerregistry/pkg/name"
+	v1 "github.com/google/go-containerregistry/pkg/v1"
+	"github.com/google/go-containerregistry/pkg/v1/remote"
+	"github.com/pkg/errors"
+)
+
+type GoContainerRegistryImage struct {
```
Comment (c-abramson) [inline pkg/registry/ggcr_image.go]: can we rename this file/struct ... maybe RemoteRegistryImage?

File: out.yaml (hunk 6 above)
Comment (matthewmcnew) [reply out.yaml]: I finally accidentally did. Gone now :)

File: pkg/dockercreds/access_checker.go (hunk 7 above)
Comment (matthewmcnew) [reply pkg/dockercreds/access_checker.go]: Sort of. We can get the status code now directly on the transport error.

**Comment by ashwin-venkatesh** [comment]
🤔 Does `dep ensure` cause a diff on your local against this branch right now? The CI pipeline failing is so bizarre.

File: pkg/registry/ggcr_image.go (hunk 8 above)
Comment (matthewmcnew) [reply pkg/registry/ggcr_image.go]: My thought is the consumers of this object will consume it through the RemoteImage interface. What makes this struct unique is that it implements that interface using  GoContainerRegistry library.
